apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ray-operator
  template:
    metadata:
      labels:
        name: ray-operator
    spec:
      serviceAccountName: ray-operator
      containers:
        - name: ray-operator
          # Replace this with the built image name
          image: rayop/ray-operator
          command:
          - ray-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ray-operator"
